### ISSUE TITLE
执行redis-full-check.linux会报go-sqlite3 cgo的错，也没说依赖什么，查不到解决方法，用了1.4.9

### ISSUE THREAD

**Issue by umena337** [aliyun/redis-full-check#116]

**Comment by yangbodong22011** [comment]
1，报错可以贴下吗？
2，用 1.4.8 的版本试试呢？

**Comment by umena337** [comment]
应该是目的redis填错了，导致的报错
用1.4.8最后可以了，

**Comment by yangbodong22011** [comment]
@umena337 之前应该是报和这个issue https://github.com/alibaba/RedisFullCheck/issues/117 一样的错，这个链接有新包，可以帮忙验证下吗？

**Comment by yangbodong22011** [comment]
https://github.com/tair-opensource/RedisFullCheck/releases  v1.4.10 修复
