### ISSUE TITLE
支持glibc2.26

### ISSUE THREAD

**Issue by steven19861130** [aliyun/redis-full-check#131]
您好，

目前项目因为公司限制最多使用的操作系统只能支持glibc2.26， 同时也没有办法进行本地编译（因为依赖太多没办法全部放在公司内部仓库）。是否可以提供一个可以在glibc2.26基础上运行的版本，非常非常感谢！

**Comment by yangbodong22011** [comment]
你好，此问题不在社区的支持范围，请理解。
