### ISSUE TITLE
err: WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by cedarwu** [aliyun/redis-full-check#36]
client.go|func: PipeRawCommand|line: 195
p.conn.Receive err: WRONGTYPE Operation against a key holding the wrong kind of value|i: 86|command: {strlen [2852130794-20190403110846544886-985389]}

CRITICAL 2019-04-03-23:15:15] (base.go:62): WRONGTYPE Operation against a key holding the wrong kind of value
panic: WRONGTYPE Operation against a key holding the wrong kind of value

goroutine 460 [running]:
full_check/checker.(*VerifierBase).FetchTypeAndLen.func2(0xc0001fa420, 0xc000899800, 0xe7, 0xe7, 0xc00383e8d0)
        /data3/cedar/redis/RedisFullCheck/src/full_check/checker/base.go:62 +0x174
created by full_check/checker.(*VerifierBase).FetchTypeAndLen
        /data3/cedar/redis/RedisFullCheck/src/full_check/checker/base.go:59 +0x20c

**Comment by vinllen** [comment]
用户打印记录：
![image](https://user-images.githubusercontent.com/6987398/55525446-a2b6a100-56c3-11e9-8fd4-d69c625b2477.png)

**Comment by vinllen** [comment]
请给一下2852130794-20190403110846544886-985389 这个key的类型
commands[i]处打印添加一个：fmt.Printf("%s\n", commands[i].params[0].([]byte))

**Comment by cedarwu** [comment]
code:
`fmt.Printf("p.conn.Receive err: %v|i: %v|command: %s|type: %s\n", err, i, commands[i], commands[i].params[0].([]byte))`

output:
p.conn.Receive err: WRONGTYPE Operation against a key holding the wrong kind of value|i: 205|command: {strlen [uc_basic_data_2852159172_1_28521591720000000000000000013797]}|type: uc_basic_data_2852159172_1_28521591720000000000000000013797
CRITICAL 2019-04-04-16:49:54] (base.go:62): WRONGTYPE Operation against a key holding the wrong kind of value
panic: WRONGTYPE Operation against a key holding the wrong kind of value

goroutine 1115 [running]:
full_check/checker.(*VerifierBase).FetchTypeAndLen.func2(0xc00010e6c0, 0xc0000b2300, 0xe0, 0xe0, 0xc0040dab10)
        /data3/cedar/redis/RedisFullCheck/src/full_check/checker/base.go:62 +0x174
created by full_check/checker.(*VerifierBase).FetchTypeAndLen
        /data3/cedar/redis/RedisFullCheck/src/full_check/checker/base.go:59 +0x20c

**Comment by vinllen** [comment]
在redis上看看uc_basic_data_2852159172_1_28521591720000000000000000013797 这个key对应的type是什么

**Comment by vinllen** [comment]
你报的这个错 应该是删除前后的类型不一样了。比如一开始scan的时候对应key的类型是string，后来删除了，又把这个key类型改为list了，那么就会报你这个错误

**Comment by vinllen** [comment]
功能待优化，处理这种key类型不断变更的情况，解决方法：

1. 不报错出现不一致直接忽略。
2. 重新获取type。重新获取还是可能有问题，万一再次变更可能会陷入不断的循环。

倾向于使用第一种方式进行优化，v1.2.3版本解决这个问题。

**Comment by vinllen** [comment]
v1.2.3分支对该问题进行修复，采用上述的第一种方式。
这个issue我先关闭，如果还有同样问题请重新打开。

**Comment by ghost** [comment]
./redis-full-check -s "A:7001;B:7004;C:7000" -p "***" -t "D:30000;E:30000;F:30000" -a "***" --sourcedbtype=1 --targetdbtype=1

这个问题在1.4.8出现如下报错
` *****] return element[WRONGTYPE Operation against a key holding the wrong kind of value] isn't type int64[redis.redisError]

goroutine 1338 [running]:
full_check/checker.(*VerifierBase).FetchTypeAndLen.func2(0xc420188680, 0xc420aa9000, 0x100, 0x100, 0xc423234e10)
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/base.go:63 +0x16b
created by full_check/checker.(*VerifierBase).FetchTypeAndLen
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/base.go:60 +0x414
[root@localhost redis-full-check-1.4.8]# ./redis-full-check -v
improve-1.4.8,8eb8326054a83dd91d1bbf55b455b4e730b612bf,go1.10.1,2020-02-12_18:32:51`

go语言不熟悉，是否为同一个问题呢，版本信息如上

redis版本: redis5 <> redis6..0.1

**Comment by vinllen** [comment]
这个应该是key的类型发生过更改，日志应该有提示报错的key是哪个
