### ISSUE TITLE
A Error come out When "govendor sync" 

### ISSUE THREAD

**Issue by fengweiyuan** [aliyun/redis-full-check#37]
$ govendor sync
Error: Remotes failed for:
        Failed for "golang.org/x/net/context" (failed to ping remote repo): unrecognized import path "golang.org/x/net/context"

**Comment by vinllen** [comment]
GOPATH设置了吗？govendor执行路径是在哪？

**Comment by fengweiyuan** [comment]
vendor.json中，前面的依赖包都成功下载了，只有最后一个"golang.org/x/net/context"一直下载不成。
这里也怀疑是公司内网的原因，如果你这边没问题，那先忽略，我自己再看看。

**Comment by vinllen** [comment]
这个应该是网络问题
