### ISSUE TITLE
What's adminauth?

### ISSUE THREAD

**Issue by fengweiyuan** [aliyun/redis-full-check#38]
type RedisHost struct {
	Addr      string                               
	Password  string                              
	TimeoutMs uint64                              
	Role      string // "source" or "target"       
	Authtype  string // "auth" or "adminauth"      
}

Here is a question:
What's adminauth？I can not find this command in Redis command table。

**Comment by vinllen** [comment]
This field is useless in current open source version, please ignore it.

**Comment by fengweiyuan** [comment]
Thanks.
