### ISSUE TITLE
panic: interface conversion: interface {} is nil, not []uint8

### ISSUE THREAD

**Issue by fanlifei** [aliyun/redis-full-check#5]
redis-full-check 执行报错：
panic: interface conversion: interface {} is nil, not []uint8

redis 版本：redis_version:3.2.9

**Comment by vinllen** [comment]
给下整体调用栈的信息，具体哪个函数core的

**Comment by vinllen** [comment]
日志贴给我吧

**Comment by fanlifei** [comment]
panic: interface conversion: interface {} is nil, not []uint8

goroutine 1 [running]:
main.(*FullCheck).Start(0xc00010c000)
        /home/fanlifei/redis-full-check/src/full_check/full_check.go:815 +0x1788
main.main()
        /home/fanlifei/redis-full-check/src/full_check/main.go:155 +0x765

**Comment by vinllen** [comment]
你能帮忙看看你redis命令行 "info Keyspace"输出是什么吗？

**Comment by fanlifei** [comment]
# Keyspace
db0:keys=43214,expires=43214,avg_ttl=0

**Comment by vinllen** [comment]
是不是没给到权限？每次启动都报错吗？你的命令行参数是怎么给的？

**Comment by fanlifei** [comment]
命令是这个：./redis-full-check -s 10.1.1.1:1234 -t 10.2.2.2:5678 -p mock_source_password -a mock_target_password --metric metric --log log --result result
每次都报错，redis有什么权限控制吗，密码是正确的

**Comment by vinllen** [comment]
权限是你自己配置的，auth可配就行。
你拉下最新的1.0.1版本，看看出错是什么？

**Comment by vinllen** [comment]
这个错误应该是地址配置有问题，请检查下源目的的配置。目前版本log信息打印不是很准确，部分错误没有抛出来，下个版本feature-1.2我们会带上。
