### ISSUE TITLE
1.4.0版本运行抛异常

### ISSUE THREAD

**Issue by Duwei92** [aliyun/redis-full-check#50]
如标题，脚本运行时异常如下：
INFO 2019-07-29-16:54:02] (main.go:54): init log success
INFO 2019-07-29-16:54:02] (full_check.go:238): sourceDbType=0, p.sourcePhysicalDBList=[meaningless]
INFO 2019-07-29-16:54:02] (full_check.go:243): db=0:keys=8
INFO 2019-07-29-16:54:02] (full_check.go:253): ---------------- start 1th time compare
INFO 2019-07-29-16:54:02] (full_check.go:278): start compare db 0
panic: interface conversion: interface {} is int64, not string

goroutine 25 [running]:
full_check/client.(*RedisClient).PipeTypeCommand(0xc420010680, 0xc420102640, 0x8, 0x8, 0x0, 0x7fc5abc10d90, 0x0, 0x0, 0xc420173b88)
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/client/client.go:247 +0x411
full_check/checker.(*VerifierBase).FetchTypeAndLen(0xc42000c880, 0xc420102640, 0x8, 0x8, 0xc420010680, 0xc42019e180)
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/base.go:36 +0x67
full_check/checker.(*FullValueVerifier).VerifyOneGroupKeyInfo(0xc42000c880, 0xc4200dc140, 0x8, 0x8, 0xc4200f8300, 0xc420010680, 0xc42019e180)
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/full_value_verifier.go:38 +0x143a
full_check/full_check.(*FullCheck).VerifyAllKeyInfo(0xc4200ea000, 0xc4200f82a0, 0xc4200f8300)
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:403 +0x412
full_check/full_check.(*FullCheck).Start.func4(0xc420112180, 0xc4200ea000, 0xc4200f82a0, 0xc4200f8300)
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:301 +0x65
created by full_check/full_check.(*FullCheck).Start
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:299 +0x886

**Comment by Duwei92** [comment]
redis集群版本为3.0.3

**Comment by vinllen** [comment]
贴一下运行参数

**Comment by Duwei92** [comment]
./redis-full-check  -s "127.0.0.1:6380;127.0.0.1:6381;127.0.0.1:6382;127.0.0.1:6383;127.0.0.1:6384;127.0.0.1:6385" -t "127.0.0.1:30001;127.0.0.1:30002;127.0.0.1:30003;127.0.0.1:30004;127.0.0.1:30005;127.0.0.1:30006" --comparemode=1 --qps=10000  --interval=10 --log log --result result

**Comment by Duwei92** [comment]
主从只能配其中一个？试了试全部配成主节点好像就可以了

**Comment by vinllen** [comment]
主从是只能配置一个，参数里面有说明

**Comment by Duwei92** [comment]
ok

**Comment by vinllen** [comment]
此处抛错不合理，后续版本进行优化：v1.4.1。

**Comment by vinllen** [comment]
部分抛错机制不合理，v1.4.1已经优化。
