### ISSUE TITLE
check结果疑问

### ISSUE THREAD

**Issue by Duwei92** [aliyun/redis-full-check#58]
用redis-shake进行集群数据同步后，使用redis-full-check进行数据检验，两个集群不一致的数据为0.然后在源集群中手动添加两条数据，再次使用redis-full-check进行数据检验，发现两个集群不一致的数据为还是为0，重复多次，有时候可以复现该问题。想问一下可能的原因是什么？

**Comment by vinllen** [comment]
源库有，但是目的库没有，这个数据是不一致的，理论上full-check能校验出来。
是不是设置了comparemode成轮廓校验了。
这个可以加下我微信对一下，redis-shake的readme的最后有我的联系方式。

**Comment by Duwei92** [comment]
ok，已加，麻烦通过以下

**Comment by vinllen** [comment]
问题已在v1.4.3版本修复，感谢反馈
