### ISSUE TITLE
1.4.3版本报不能执行这个文件

### ISSUE THREAD

**Issue by liuwenya1234** [aliyun/redis-full-check#61]
1.4.3版本报不能执行这个文件
-bash: ./redis-full-check: cannot execute binary file
执行参数如下：
./redis-full-check -s "192.168.1.108:6379" -t "192.168.1.108:6380" --comparemode=1 --qps=10000 --interval=10 --log log --result result

**Comment by vinllen** [comment]
这个是Linux环境的二进制执行文件，你是别的环境吧？

**Comment by liuwenya1234** [comment]
我是centos的linux环境的，是linux环境呢

发自我的 iPhone

**Comment by vinllen** [comment]
神奇了，这个先自己编译好了，README上有编译的方式

**Comment by liuwenya1234** [comment]
本地没有编译环境啊！

发自我的 iPhone

**Comment by vinllen** [comment]
ldd看下依赖的库是否缺少了

**Comment by liuwenya1234** [comment]
idd是什么啊，不懂啊。

发自我的 iPhone

**Comment by vinllen** [comment]
LDD，看下链接库

**Comment by liuwenya1234** [comment]
在哪里看啊。

发自我的 iPhone

**Comment by vinllen** [comment]
执行命令`ldd redis-shake`。这个可能是库缺少导致，自己编译的话下载一个govendor就可以编译了

**Comment by liuwenya1234** [comment]
这个工具不能单独使用？一定要和redis-shake配合？

发自我的 iPhone

**Comment by vinllen** [comment]
发错了 `ldd redis-full-check`

**Comment by liuwenya1234** [comment]
执行ldd ，报not a dynamic executable

发自我的 iPhone

**Comment by vinllen** [comment]
你加下我微信好了，我把govendor二进制发给你 应该可以编译的，redis-shake的readme上能找到我

**Comment by liuwenya1234** [comment]
加你了，麻烦同意下。

发自我的 iPhone
