### ISSUE TITLE
依赖的 github.com/vinllen/redis-go-cluster 的CRC算法 是不是存在bug

### ISSUE THREAD

**Issue by shuff1e** [aliyun/redis-full-check#68]
https://github.com/vinllen/redis-go-cluster/blob/master/crc16.go
```
func crc16(buf string) uint16 {
	var crc uint16
	for _, n := range buf {
		crc = (crc << uint16(8)) ^ crc16tab[((crc>>uint16(8))^uint16(n))&0x00FF];
	}
	return crc
}
```

![image](https://user-images.githubusercontent.com/30022834/68602059-95c32100-04e0-11ea-8d3b-9400155e1042.png)
是不是应该改为byte的方式？
rune是int32的别名，

比如key是两个汉字，"高天"，
发送给redis的key的字节数组为0xe9ab 98e5 a4a9
![1573526575408](https://user-images.githubusercontent.com/30022834/68637324-38a78980-0539-11ea-84ab-a4dd2272c297.jpeg)
是byte而不是rune，
cluster.Do("llen","高天")中也是会运行到kRespMove分支的

**Comment by vinllen** [comment]
赞，感谢反馈，这个的确有Bug。这个在shake和fullCheck里面都有问题，没有考虑到中文的Bug。你留个邮箱，我写到shake的contributor list里面！

**Comment by shuff1e** [comment]
> 赞，感谢反馈，这个的确有Bug。这个在shake和fullCheck里面都有问题，没有考虑到中文的Bug。你留个邮箱，我写到shake的contributor list里面！

sfxu@foxmail.com

**Comment by vinllen** [comment]
v1.4.5版本已发布

**Comment by shuff1e** [comment]
> v1.4.5版本已发布

https://github.com/alibaba/RedisShake/blob/develop/src/redis-shake/common/crc16.go
这个的CRC算法也改下吧

**Comment by vinllen** [comment]
嗯……有空的话也可以帮提个PR

**Comment by shuff1e** [comment]
PR是什么意思

**Comment by shuff1e** [comment]
> PR是什么意思

明白了……后续尝试提交下pull request

**Comment by vinllen** [comment]
嗯嗯 pull request
