### ISSUE TITLE
github.com/vinllen/redis-go-cluster/node.go中readLine方法bug

### ISSUE THREAD

**Issue by shuff1e** [aliyun/redis-full-check#73]
RunBatch -> doBatch -> conn.receive() -> conn.readReply() -> conn.readLine()
发现这个地方由于readLine方法的bug，未能读取整个value，
从而len(line) != n，然后返回错误：invalid response
```
	case '$':
		n, err := parseLen(line[1:])
		if n < 0 || err != nil {
			return nil, err
		}

		line, err = conn.readLine()
		if err != nil {
			return nil, err
		}
		if len(line) != n {
			return nil, errors.New("invalid response")
		}
```
其中readLine方法为：https://github.com/vinllen/redis-go-cluster/blob/master/node.go#L338
```
// readLine read a single line terminated with CRLF.
func (conn *redisConn) readLine() ([]byte, error) {
	var line []byte
	for {
		p, err := conn.br.ReadBytes('\n')
		if err != nil {
			return nil, err
		}

		n := len(p) - 2
		if n < 0 {
			return nil, errors.New("invalid response")
		}

		// bulk string may contain '\n', such as CLUSTER NODES
		if p[n] != '\r' {
			if line != nil {
				line = append(line, p[:]...)
			} else {
				line = p
			}
			continue
		}

		if line != nil {
			return append(line, p[:n]...), nil
		} else {
			return p[:n], nil
		}
	}
}
```
如果读取的value本身就含有"\r\n"，就无法读取整个value，只能读取一部分。   
例如hgetall返回的响应为这种：
value中间有"\r\n"  
![image](https://user-images.githubusercontent.com/30022834/69032356-394b8e80-0a17-11ea-8713-e6499270d4f7.png)
或者这种：
value结尾有"\r\n"  
![image](https://user-images.githubusercontent.com/30022834/69032380-49636e00-0a17-11ea-95dd-989a786993dc.png)
就会发现 len(line) != n  
然后  
return nil, errors.New("invalid response")

**Comment by shuff1e** [comment]
直接
```
		n, err := parseLen(line[1:])
		if n < 0 || err != nil {
			return nil, err
		}

		buf := make([]byte,n)
		io.ReadFull(conn.br,buf)
```
比用"\r\n"判断更好？

**Comment by vinllen** [comment]
看起来这里的确是有问题。

**Comment by shuff1e** [comment]
啥时候能fix掉(^_^)

**Comment by vinllen** [comment]
今天下午或者明天我发个版本

**Comment by vinllen** [comment]
人力问题 暂时delay至下周

**Comment by vinllen** [comment]
1.4.6已发布
